routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', 'GraphicController@index')->name('graphic.index');
Route::get('/matrix', 'GraphicController@matrix')->name('graphic.matrix');
Route::get('/table', 'GraphicController@table')->name('graphic.table');
Route::get('/puml/group-render/{property}', 'GraphicController@index')->name('graphic.groupRender');
Route::get('/puml/interface/{interface}', 'GraphicController@interface')->name('graphic.interface');
Route::get('/puml/application/{application}', 'GraphicController@application')->name('graphic.application');
Route::get('/puml/database/{database}', 'GraphicController@database')->name('graphic.database');

Route::resource('/applications', 'ApplicationController');
Route::resource('/databases', 'DatabaseController');
Route::resource('/application-interfaces', 'ApplicationInterfaceController');
Route::resource('/properties', 'PropertyController');
Route::resource('/property-options', 'PropertyOptionController');

app/Models/Application.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Application extends Model
{
    use HasFactory;

    public const LIFECYCLE_STATUS_PLANNED = 1;
    public const LIFECYCLE_STATUS_IN_USE = 10;
    public const LIFECYCLE_STATUS_TO_BE_KILLED = -1;

    public const LIFECYCLE_STATUS = [
        self::LIFECYCLE_STATUS_PLANNED      => 'planned',
        self::LIFECYCLE_STATUS_IN_USE       => 'in use',
        self::LIFECYCLE_STATUS_TO_BE_KILLED => 'to be killed',
    ];

    protected $fillable = ['name', 'description', 'lifecycle_status', 'is_user_application'];

    /**
     * Get all applications sorted
     *
     * @return \Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection
     */
    public static function allSorted(Builder $baseQuery = null)
    {
        return ($baseQuery ?? self::query())
            ->orderBy('name')
            ->orderBy('description')
            ->get();
    }

    /**
     * Get the identifier of the puml element
     *
     * @return string
     */
    public function getPumlName()
    {
        return 'app_' . $this->id;
    }

    /**
     * Get the displayed title of the puml element
     *
     * @return string
     */
    public function getPumlTitle(): string
    {
        $before = '<b><u>';
        $after = ' </u></b>';

        return $before . chunk_split(strip_tags($this->getTitle()), 35, $after . '\n' . $before) . $after;
    }

    /**
     * Get the displayed title for forms (max-length is 100 characters)
     *
     * @return string
     */
    public function getTitle(): string
    {
        $title = Str::limit($this->name, 30);

        if (!empty($this->description)) {
            $title .= ' | ' . Str::limit($this->description, 100);
        }

        return $title;
    }

    /**
     * Get background color based on type
     *
     * @return string
     */
    public function getPumlBackgroundColor(): string
    {
        switch ($this->lifecycle_status) {
            case self::LIFECYCLE_STATUS_PLANNED:
                return '#57BF45';
            case self::LIFECYCLE_STATUS_TO_BE_KILLED:
                return '#FF6765';
            default:
                return '';
        }
    }

    /**
     * Get name of the group for grouped puml diagram
     *
     * @param Property $groupProperty
     *
     * @return string
     */
    public function getPumlGroupName(Property $groupProperty): string
    {
        $applicationProperty = $this
            ->application_properties()
            ->where(['property_id' => $groupProperty->id])
            ->first();
        return ($applicationProperty ?? new \App\Models\ApplicationProperty())->getPumlValue();
    }

    /** ##### Relations ##### */

    public function application_interfaces()
    {
        return $this->hasMany(ApplicationInterface::class);
    }

    public function usages()
    {
        return $this->hasMany(Usage::class);
    }

    public function database_connections()
    {
        return $this->hasMany(DatabaseConnection::class);
    }

    public function application_properties()
    {
        return $this->hasMany(ApplicationProperty::class);
    }
}

app/Http/Controllers/ApplicationController.php
<?php

namespace App\Http\Controllers;

use App\Models\ApplicationInterface;
use App\Models\Application;
use App\Models\ApplicationProperty;
use App\Models\Property;
use App\Models\Usage;
use Illuminate\Http\Request;

class ApplicationController extends Controller
{
    public const VIEW_PREFIX = 'application';
    public const ROUTE_PREFIX = 'applications';
    public const TITLE_PREFIX = 'labels.titles.' . self::VIEW_PREFIX;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $applications = Application::allSorted();
        $title = __(self::TITLE_PREFIX . '.index');
        return view(self::VIEW_PREFIX . '.index', compact('title', 'applications'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $applicationProperties = [];

        foreach (Property::all() as $property) {
            $applicationProperties[] = [
                'property_id' => $property->id,
                'name'        => $property->name,
                'is_enum'     => $property->is_enum,
                'options'     => $property->is_enum ? $property->getOptions() : null,
            ];
        }

        $usages = array_map(function ($appInterface) {
            return [
                'target_application_id'           => $appInterface['application_id'],
                'target_application_interface_id' => $appInterface['id'],
                'name'                            => Application::query()->find($appInterface['application_id'])->getTitle() . ': ' . $appInterface['name'],
            ];
        }, ApplicationInterface::allSorted()->toArray());

        $title = __(self::TITLE_PREFIX . '.create');
        return view(self::VIEW_PREFIX . '.createOrUpdate', compact('title', 'applicationProperties', 'usages'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $application = new Application($request->only([
            'name',
            'description',
            'lifecycle_status',
            'is_user_application'
        ]));
        $application->saveOrFail();

        foreach ($request->get('applicationProperties') ?? [] as $propertyId => $propertyValue) {
            if (empty($propertyValue)) {
                continue;
            }
            $applicationProperty = new ApplicationProperty([
                'application_id' => $application->id,
                'property_id'    => $propertyId,
            ]);

            if (Property::query()->find($propertyId)->is_enum) {
                $applicationProperty->property_option_id = $propertyValue;
            } else {
                $applicationProperty->value = $propertyValue;
            }

            $applicationProperty->saveOrFail();
        }

        foreach ($request->get('usages') ?? [] as $usedInterfaceId) {
            $usage = new Usage(['application_id' => $application->id, 'application_interface_id' => $usedInterfaceId]);
            $usage->saveOrFail();
        }

        return redirect()
            ->route(self::ROUTE_PREFIX . '.index')
            ->with('success', __('labels.messages.entry-created', ['type' => 'Application']));
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Application $application
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Application $application)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Application $application
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Application $application)
    {
        $applicationProperties = array_map(function ($property) use ($application) {
            $applicationProperty = ApplicationProperty::query()->where([
                'application_id' => $application->id,
                'property_id'    => $property['id'],
            ])->first();

            $propertyModel = Property::query()->find($property['id']);
            $isEnum = $propertyModel->is_enum ?? false;

            return [
                'property_id' => $property['id'],
                'name'        => $property['name'],
                'is_enum'     => $isEnum,
                'value'       => $isEnum ? $applicationProperty->property_option_id ?? '' : ($applicationProperty->value ?? ''),
                'options'     => $isEnum ? $propertyModel->getOptions() : null,
            ];

        }, Property::all()->toArray());


        $usages = array_map(function ($appInterface) use ($application) {
            return [
                'target_application_id'           => $appInterface['application_id'],
                'target_application_interface_id' => $appInterface['id'],
                'name'                            => Application::query()->find($appInterface['application_id'])->getTitle() . ': ' . $appInterface['name'],
                'value'                           => Usage::query()->where([
                    'application_id'           => $application->id,
                    'application_interface_id' => $appInterface['id']
                ])->exists(),
            ];
        }, ApplicationInterface::allSorted()->toArray());

        $title = __(self::TITLE_PREFIX . '.update');
        return view(self::VIEW_PREFIX . '.createOrUpdate',
            compact('title', 'application', 'applicationProperties', 'usages'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Application  $application
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Application $application)
    {
        $application->fill($request->only(['name', 'description', 'lifecycle_status']));
        $application->saveOrFail();

        foreach ($request->get('applicationProperties') ?? [] as $propertyId => $propertyValue) {
            $applicationProperty = ApplicationProperty::query()->firstOrCreate([
                'application_id' => $application->id,
                'property_id'    => $propertyId
            ]);

            if (empty($propertyValue)) {
                $applicationProperty->delete();
                continue;
            }

            if ($applicationProperty->property->is_enum) {
                $applicationProperty->fill(['value' => null, 'property_option_id' => $propertyValue]);
            } else {
                $applicationProperty->fill(['value' => $propertyValue]);
            }

            $applicationProperty->saveOrFail();
        }

        foreach ($request->get('usages') ?? [] as $usedInterfaceId) {
            $usage = Usage::query()->firstOrCreate([
                'application_id'           => $application->id,
                'application_interface_id' => $usedInterfaceId
            ]);
            $usage->saveOrFail();
        }

        /** @var Usage $usage */
        foreach (Usage::query()->where(['application_id' => $application->id])->get() as $usage) {
            if (!in_array($usage->application_interface_id, $request->get('usages') ?? [])) {
                $usage->delete();
            }
        }

        return redirect()
            ->route(self::ROUTE_PREFIX . '.index')
            ->with('success', __('labels.messages.entry-updated', ['type' => 'Application']));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Application $application
     *
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Application $application)
    {
        $application->delete();
        return redirect()
            ->route(self::ROUTE_PREFIX . '.index')
            ->with('success', __('labels.messages.entry-deleted', ['type' => 'Application']));
    }
}

resources/views/application/createOrUpdate.blade.php
@extends('layout')

@section('content')
    {{ Aire::resourceful($application ?? new \App\Models\Application()) }}

    @php($isUserApp = $application->is_user_application ?? request('user_app') ?? 0)
    {{ Aire::hidden('is_user_application', $isUserApp)->defaultValue(0) }}
    {{ Aire::input('name', 'Name') }}

    @if($isUserApp)
        @php($title .= ' (User)')
        {{ Aire::hidden('description', 'User-Application') }}
        {{ Aire::hidden('lifecycle_status', \App\Models\Application::LIFECYCLE_STATUS_IN_USE) }}
    @else
        {{ Aire::input('description', 'Description') }}
        {{ Aire::select(\App\Models\Application::LIFECYCLE_STATUS, 'lifecycle_status', 'Lifecycle Status') }}

        @foreach($applicationProperties as $applicationProperty)
            @if($applicationProperty['is_enum']??false)
                {{ Aire::select(
                    $applicationProperty['options'],
                    'applicationProperties['.$applicationProperty['property_id'].']',
                    $applicationProperty['name']
                )->value($applicationProperty['value'] ?? '') }}
            @else
                {{ Aire::input(
                    'applicationProperties['.$applicationProperty['property_id'].']',
                    $applicationProperty['name']
                )->value($applicationProperty['value'] ?? '') }}
            @endif
        @endforeach
    @endif

    <h3>Usages</h3>
    @php($options=[])
    @php($values=[])
    @php(array_map(function ($v)use (&$options, &$values){$options[$v['target_application_interface_id']]=$v['name']; if ($v['value']??false){$values[]=$v['target_application_interface_id'];}},$usages ))

    {{ Aire::select($options, 'usages')
        ->multiple()
        ->value($values)
        ->style('height: ' . min(count($usages)*25, 300) . 'px;') }}

    {{ Aire::submit() }}

    {{ Aire::close() }}
@endsection

resources/views/application/index.blade.php
@extends('layout')

@section('content')
    @include('components.button-create', ['route' => route('applications.create')])
    @include('components.button-create', ['route' => route('applications.create', ['user_app' => true]), 'label' => __('labels.buttons.add_new').' User-Application'])
    <br><br>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>Lifecycle Status</th>
            <th></th>
            <th></th>
        </tr>
        @foreach($applications as $application)
            <tr id="entry-{{ $application->id }}">
                <th>{{ $application->id }}</th>
                <td>{{ $application->name }}</td>
                <td>{{ $application->description }}</td>
                <td style="min-width: 130px">
                    <span class="dot" style="background-color: {{ $application-> getPumlBackgroundColor() }}"></span>
                    {{ \App\Models\Application::LIFECYCLE_STATUS[$application->lifecycle_status] }}
                </td>
                <td>@include('components.button-edit', ['route' => route('applications.edit', compact('application'))])</td>
                <td>@include('components.button-delete', ['route' => route('applications.destroy', compact('application'))])</td>
            </tr>
        @endforeach
    </table>
@endsection