routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', 'GraphicController@index')->name('graphic.index');
Route::get('/matrix', 'GraphicController@matrix')->name('graphic.matrix');
Route::get('/table', 'GraphicController@table')->name('graphic.table');
Route::get('/puml/group-render/{property}', 'GraphicController@index')->name('graphic.groupRender');
Route::get('/puml/interface/{interface}', 'GraphicController@interface')->name('graphic.interface');
Route::get('/puml/application/{application}', 'GraphicController@application')->name('graphic.application');
Route::get('/puml/database/{database}', 'GraphicController@database')->name('graphic.database');

Route::resource('/applications', 'ApplicationController');
Route::resource('/databases', 'DatabaseController');
Route::resource('/application-interfaces', 'ApplicationInterfaceController');
Route::resource('/properties', 'PropertyController');
Route::resource('/property-options', 'PropertyOptionController');

app/Models/PropertyOption.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PropertyOption extends Model
{
    use HasFactory;

    protected $fillable = ['property_id', 'name', 'color', 'description'];

    protected static function boot()
    {
        parent::boot();

        self::saving(function (self $propOpt) {
            if (empty($propOpt->color) || $propOpt->color === '#000000') {
                $propOpt->color = null;
            }
        });
    }

    /** ##### Relations ##### */

    public function property()
    {
        return $this->belongsTo(Property::class);
    }

    /**
     * Get all property-options order by its properties
     *
     * @return \Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection
     */
    public static function allSorted()
    {
        return self::query()
            ->join('properties', 'properties.id', '=', 'property_options.property_id')
            ->select(['property_options.*'])
            ->orderBy('properties.name')
            ->orderBy('property_options.name')
            ->get();
    }
}

app/Http/Controllers/PropertyOptionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Property;
use App\Models\PropertyOption;
use Illuminate\Http\Request;

class PropertyOptionController extends Controller
{
    public const VIEW_PREFIX = 'property-option';
    public const ROUTE_PREFIX = 'property-options';
    public const TITLE_PREFIX = 'labels.titles.' . self::VIEW_PREFIX;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $propertyOptions = PropertyOption::allSorted();
        $title = __(self::TITLE_PREFIX . '.index');
        return view(self::VIEW_PREFIX . '.index', compact('title', 'propertyOptions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $properties = [];
        foreach (Property::query()->where('is_enum', true)->get() as $property) {
            $properties[$property->id] = $property->name;
        }

        $title = __(self::TITLE_PREFIX . '.create');
        return view(self::VIEW_PREFIX . '.createOrUpdate', compact('title', 'properties'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     * @throws \Throwable
     */
    public function store(Request $request)
    {
        $propertyOption = new PropertyOption($request->except(['_token']));
        $propertyOption->saveOrFail();
        return redirect()
            ->route(self::ROUTE_PREFIX . '.index')
            ->with('success', __('labels.messages.entry-created', ['type' => 'Property-Option']));
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\PropertyOption $propertyOption
     *
     * @return \Illuminate\Http\Response
     */
    public function show(PropertyOption $propertyOption)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\PropertyOption $propertyOption
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(PropertyOption $propertyOption)
    {
        $properties = [];
        foreach (Property::all() as $property) {
            $properties[$property->id] = $property->name;
        }

        $title = __(self::TITLE_PREFIX . '.update');
        return view(self::VIEW_PREFIX . '.createOrUpdate', compact('title', 'propertyOption', 'properties'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request   $request
     * @param \App\Models\PropertyOption $propertyOption
     *
     * @return \Illuminate\Http\Response
     * @throws \Throwable
     */
    public function update(Request $request, PropertyOption $propertyOption)
    {
        $propertyOption->fill($request->except(['_token']));
        $propertyOption->saveOrFail();
        return redirect()
            ->route(self::ROUTE_PREFIX . '.index')
            ->with('success', __('labels.messages.entry-updated', ['type' => 'Property-Option']));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\PropertyOption $propertyOption
     *
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(PropertyOption $propertyOption)
    {
        $propertyOption->delete();
        return redirect()
            ->route(self::ROUTE_PREFIX . '.index')
            ->with('success', __('labels.messages.entry-deleted', ['type' => 'Property-Option']));
    }
}

resources/views/property-option/createOrUpdate.blade.php
@extends('layout')

@section('content')
    {{ Aire::resourceful($propertyOption ?? new \App\Models\PropertyOption(), 'property-options') }}
    {{ Aire::input('name', 'Name') }}
{{--    {{ Aire::input('description', 'Description') }}--}}
    {{ Aire::select($properties, 'property_id', 'Property') }}
    {{ Aire::color('color', 'Color')->defaultValue('#000000')->helpText('Set color to black to reset') }}
    {{ Aire::submit() }}
    {{ Aire::close() }}
@endsection

resources/views/property-option/index.blade.php
@extends('layout')

@section('content')
    @include('components.button-create', ['route' => route('property-options.create')])
    <br><br>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Property name</th>
            <th>Color</th>
            <th></th>
            <th></th>
        </tr>
        @foreach($propertyOptions as $propertyOption)
            <tr id="entry-{{ $propertyOption->id }}">
                <th>{{ $propertyOption->id }}</th>
                <td>{{ $propertyOption->name }}</td>
                <td>{{ $propertyOption->property->name }}</td>
                <td>
                    @if($propertyOption->color)
                        <span class="dot" style="background-color: {{ $propertyOption->color }}"></span>
                    @else
                        -
                    @endif
                </td>
                <td>@include('components.button-edit', ['route' => route('property-options.edit', ['property_option'=> $propertyOption])])</td>
                <td>@include('components.button-delete', ['route' => route('property-options.destroy', ['property_option'=> $propertyOption])])</td>
            </tr>
        @endforeach
    </table>
@endsection